server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    registry-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost