server:
  port: 8083
spring:
  cloud:
    server:
      git:
        default-label: config-server
        uri: https://github.com/KellyCardenas/paymentchain
        search-paths: config-data
  application:
    name: config-service
